services:
  file:
    build:
      context: .
      dockerfile: dev.dockerfile
    env_file:
      - ./.env
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - db:/app/data
      - upload:/app/upload
volumes:
  db:
  upload: